# plex_auth/utils/exceptions.py


class PlexAPIError(Exception):
    """Custom exception for Plex API related errors"""

    pass
